name: Auto Merge

on:
  pull_request_target:

permissions:
  contents: read

jobs:
  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Not implemented yet
        run: echo "TODO: Implement Auto Merge workflow."
