name: Matrix CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Not implemented yet
        run: echo "TODO: Implement Matrix CI workflow."
